#服务端口配置
server:
  port: 8083
  context-path: /bysj
spring:
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    platform: mysql
    url: jdbc:mysql://localhost:3306/bysj?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: sa
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: bysj
  thymeleaf:
    cache: false
    content-type: text/html
    encoding: UTF-8
    enabled: true
    mode: HTML5
    suffix: .html
    prefix: classpath:/templates/
  http:
    multipart:
      max-file-size: 100Mb
      max-request-size: 100Mb

